//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthleteFitnessTest
    {
        public int Id { get; set; }
        public int AthleteId { get; set; }
        public int FitnessTestId { get; set; }
        public bool Completed { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual FitnessTest FitnessTest { get; set; }
    }
}
