//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lifts.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiftsDbEntities : DbContext
    {
        public LiftsDbEntities()
            : base("name=LiftsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FitnessTest> FitnessTests { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Athlete> Athletes { get; set; }
        public virtual DbSet<AthleteFitnessTest> AthleteFitnessTests { get; set; }
    }
}
